---
- name: Install logstash
  yum: name={{logstash_url}} state=present

- name: change logstash configuration
  template: src=network.conf.j2 dest=/etc/logstash/conf.d/network.conf

- name: enable logstash service
  service: name=logstash enabled=yes state=restarted
