---
- name: Install Nginx
  yum: name=nginx state=present

- name: change nginx main configuration
  template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf

- name: change nginx reverse proxy to tomcat configuration
  template: src=tomcat.conf.j2 dest=/etc/nginx/conf.d/tomcat.conf

- name: enable nginx service
  service: name=nginx enabled=yes state=restarted
