---
- name: Install libtool-ltdl
  yum: name="http://{{filesrv}}/files/monitor/libtool-ltdl-2.4.2-20.el7.x86_64.rpm" state=present

- name: Install unixODBC
  yum: name="http://{{filesrv}}/files/monitor/unixODBC-2.3.1-11.el7.x86_64.rpm" state=present

- name: Install zabbix-agent
  yum: name="http://{{filesrv}}/files/monitor/zabbix-agent-3.0.0-1.el7.x86_64.rpm" state=present

- name: change zabbix-agent configuration
  template: src=zabbix_agentd.conf.j2 dest=/etc/zabbix/zabbix_agentd.conf backup=no

- name: enable zabbix-agent service
  service: name=zabbix-agent enabled=yes state=restarted
